### ISSUE TITLE
Hi, can't require C module

### ISSUE THREAD

**Issue by robertlzj** [PG1003/dogfood#1]
Hi, this project is so nice.
Lua modules embed or not works fine.
But process is blocked when require C module (.dll).
I test some dynamic libs - '[lfs](https://lunarmodules.github.io/luafilesystem/)', 'socket', 'iuplua', 'gbk'.
Demo:
1. `print(pcall(require,'lfs'))` in test.lua  
  lfs is in the same directory.
2. 'dogfood.exe test.exe test' in cmd
3. 'test.exe' under cmd.

**Comment by PG1003** [comment]
Hello, I'm sorry to react this late.
Nice to hear you like it!
I will investigate your issue.

**Comment by PG1003** [comment]
I've tried to reproduce your issue but did not got the same result.
But instead of the 'lfs' I used my own filesystem module and that worked.

The following three points may help you.

Do you use the pre-build binary?
In that case, then issue could be that the pre-build dogfood binaries are build with MSVC which may not be compatible with your Lua Rocks configuration (I assume).

Are the C modules and the dogfood executable of the same platform (x86/x64)?

Are you sure that you placed all the dependencies/DLLs required by 'lfs', 'socked' 'iuplua', 'gbk' are placed too in the same folder as these C modules? You can use [Depdency Walker](https://dependencywalker.com) to figure out what is missing.

**Comment by robertlzj** [comment]
Hi,
I use dogfood53_win_x86-32.zip and C module for lua 5.3.
I attach 'lfs.dll' and all the demo. I'm not sure compile compatible problem.

I use pre-compile binary for lfs.dll and lua5.3 from official, generally not suffer any compatible problem.
But the issue presents like a lua5.1 interpreter handles a 5.3 module - process blocks till some timeout, then program stop, without any error message.

> Are the C modules and the dogfood executable of the same platform (x86/x64)?   

Yes, they are. Otherwise, there will be prompt: error loading module 'lfs' from file 'lfs.dll', %1 not a valid Win32 application.

> Are you sure that you placed all the dependencies.  

Yes. Otherwise, it will prompt "module 'lfs' not found".

Demo:
```lua
--test.lua
print(_VERSION)
package.path=''
package.cpath='?.dll'
print(package.cpath)
--	require'lfs'
local _,lfs=assert(pcall(require,'lfs'))
print(lfs)
print'test OK'
```

Step:
1. `dogfood.exe test.exe test` in cmd.
2. `test.exe`, will get
  > D:>test.exe
  > Lua 5.3
  > ?.dll
  > 
  > D:>

Files:
[dogfood_test.zip](https://github.com/PG1003/dogfood/files/12644456/dogfood_test.zip)
- lfs.dll
- test.exe
- test.lua

Thanks for your work, again~

**Comment by PG1003** [comment]
The lfs C module required lua53.dll.
However when I added lua53.dll then a 'multiple Lua VMs detected' message was displayed in the command prompt.

The pre-build Lua binaries are statically build with Lua which effectively disables support for C modules.
So, dogfood needs to be dynamically linked to support C modules.

I really liked the single dogfood executable without dependencies.
Its possible to embed a DDL in an executable but that requires a change to dog.c and the Visual Studio project files. I will try this but I'm not sure how it turns out.

**Comment by PG1003** [comment]
I've managed to embed Lua53.dll into the dogfood executable.

[This](https://github.com/PG1003/dogfood/files/12651560/dogfood53.zip) zip contains a debug build of dogfood for Lua 5.3
It runs your test without errors.
Can you try this build with other libraries?

**Comment by PG1003** [comment]
A new release of dogfood has been made.
Also the pre-build binaries are updated to include the fix for your issue.
